In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("damerajee/simple-chatbot-dataset")

print("Path to dataset files:", path)

Path to dataset files: /home/vashuthegreat/.cache/kagglehub/datasets/damerajee/simple-chatbot-dataset/versions/1

In [6]:
import os
import shutil

In [7]:
os.listdir(path)

['intents.json']

In [8]:
import pandas as pd

In [9]:
pd.read_json(os.path.join(path, 'intents.json'),)

                                              intents
0   {'tag': 'greeting', 'patterns': ['Hi', 'Hey', ...
1   {'tag': 'weather', 'patterns': ['What's the we...
2   {'tag': 'hobbies', 'patterns': ['What are your...
3   {'tag': 'music', 'patterns': ['What's your fav...
4   {'tag': 'movies', 'patterns': ['What's a good ...
5   {'tag': 'farewell', 'patterns': ['Goodbye', 'S...
6   {'tag': 'informal_question', 'patterns': ['Wha...
7   {'tag': 'formal_question', 'patterns': ['Could...
8   {'tag': 'math_operations', 'patterns': ['What ...
9   {'tag': 'math_formulas', 'patterns': ['What's ...
10  {'tag': 'prime_numbers', 'patterns': ['Is 23 a...
11  {'tag': 'motivation', 'patterns': ['I feel dem...
12  {'tag': 'team_building', 'patterns': ['How can...
13  {'tag': 'supporting_others', 'patterns': ['How...
14  {'tag': 'overcoming_adversity', 'patterns': ['...
15  {'tag': 'geometry_concepts', 'patterns': ['Exp...
16  {'tag': 'math_puzzles', 'patterns': ['Solve th...
17  {'tag': 'shakespeare_poems', 'patterns': ['Rea...

In [10]:
import json
import pandas as pd
import random

# load your file
with open(os.path.join(path, 'intents.json'), "r", encoding="utf-8") as f:
    data = json.load(f)

pairs = []

# intents list
intents = data["intents"]

for intent in intents:
    patterns = intent.get("patterns", [])
    responses = intent.get("responses", [])

    # one-to-one mapping (cycle responses if needed)
    for i, pattern in enumerate(patterns):

        response = responses[i % len(responses)]  # safe mapping

        pairs.append({
            "user": pattern,
            "assistant": response,
            "tag": intent.get("tag")
        })

# convert to DataFrame
df = pd.DataFrame(pairs)

print(df.head())

# save
# df.to_csv("chat_dataset.csv", index=False)

       user                               assistant       tag
0        Hi                              Hey there!  greeting
1       Hey            Hello! How can I assist you?  greeting
2     Howdy                     Hi, how's it going?  greeting
3     Hello                   Hey, nice to see you!  greeting
4  Hi there  Hi there! What can I do for you today?  greeting

In [11]:
df

,user,assistant,tag
0,Hi,Hey there!,greeting
1,Hey,Hello! How can I assist you?,greeting
2,Howdy,"Hi, how's it going?",greeting
3,Hello,"Hey, nice to see you!",greeting
4,Hi there,Hi there! What can I do for you today?,greeting
...,...,...,...
59,Can you figure out 25 divided by 5 plus 3?,25 divided by 5 plus 3 equals 8.,math_puzzles
60,"What's the missing number in this sequence: 2,...","The missing number in the sequence is 8, as it...",math_puzzles
61,Read me a poem by Shakespeare.,Certainly! Here's a beautiful poem by William ...,shakespeare_poems
62,Share a Shakespearean poem with me.,Certainly! Here's a beautiful poem by William ...,shakespeare_poems
63,Let me hear a poem written by Shakespeare.,Certainly! Here's a beautiful poem by William ...,shakespeare_poems

In [12]:
def add_tag_user(text=""):
    return f"User: {text}\n"


def add_tag_assistant(text=""):
    return f"Assistant: {text}<|endoftext|>\n"


df['user'] = df['user'].apply(add_tag_user)
df['assistant'] = df['assistant'].apply(add_tag_assistant)

In [13]:
df

,user,assistant,tag
0,User: Hi\n,Assistant: Hey there!<|endoftext|>\n,greeting
1,User: Hey\n,Assistant: Hello! How can I assist you?<|endof...,greeting
2,User: Howdy\n,"Assistant: Hi, how's it going?<|endoftext|>\n",greeting
3,User: Hello\n,"Assistant: Hey, nice to see you!<|endoftext|>\n",greeting
4,User: Hi there\n,Assistant: Hi there! What can I do for you tod...,greeting
...,...,...,...
59,User: Can you figure out 25 divided by 5 plus ...,Assistant: 25 divided by 5 plus 3 equals 8.<|e...,math_puzzles
60,User: What's the missing number in this sequen...,Assistant: The missing number in the sequence ...,math_puzzles
61,User: Read me a poem by Shakespeare.\n,Assistant: Certainly! Here's a beautiful poem ...,shakespeare_poems
62,User: Share a Shakespearean poem with me.\n,Assistant: Certainly! Here's a beautiful poem ...,shakespeare_poems
63,User: Let me hear a poem written by Shakespear...,Assistant: Certainly! Here's a beautiful poem ...,shakespeare_poems

In [14]:
df["text"] = df["user"] + df["assistant"]

In [15]:
df

,user,assistant,tag,text
0,User: Hi\n,Assistant: Hey there!<|endoftext|>\n,greeting,User: Hi\nAssistant: Hey there!<|endoftext|>\n
1,User: Hey\n,Assistant: Hello! How can I assist you?<|endof...,greeting,User: Hey\nAssistant: Hello! How can I assist ...
2,User: Howdy\n,"Assistant: Hi, how's it going?<|endoftext|>\n",greeting,"User: Howdy\nAssistant: Hi, how's it going?<|e..."
3,User: Hello\n,"Assistant: Hey, nice to see you!<|endoftext|>\n",greeting,"User: Hello\nAssistant: Hey, nice to see you!<..."
4,User: Hi there\n,Assistant: Hi there! What can I do for you tod...,greeting,User: Hi there\nAssistant: Hi there! What can ...
...,...,...,...,...
59,User: Can you figure out 25 divided by 5 plus ...,Assistant: 25 divided by 5 plus 3 equals 8.<|e...,math_puzzles,User: Can you figure out 25 divided by 5 plus ...
60,User: What's the missing number in this sequen...,Assistant: The missing number in the sequence ...,math_puzzles,User: What's the missing number in this sequen...
61,User: Read me a poem by Shakespeare.\n,Assistant: Certainly! Here's a beautiful poem ...,shakespeare_poems,User: Read me a poem by Shakespeare.\nAssistan...
62,User: Share a Shakespearean poem with me.\n,Assistant: Certainly! Here's a beautiful poem ...,shakespeare_poems,User: Share a Shakespearean poem with me.\nAss...
63,User: Let me hear a poem written by Shakespear...,Assistant: Certainly! Here's a beautiful poem ...,shakespeare_poems,User: Let me hear a poem written by Shakespear...

In [16]:
import os
file_name="data_emoji.txt"
if os.path.exists(file_name):
    os.remove(file_name)

In [17]:
with open(file_name, "a") as f:
    for line in df["text"]:
        f.write(line)

In [18]:
with open(file_name,"r") as f:
  a=f.read()
  print(a)

User: Hi
Assistant: Hey there!<|endoftext|>
User: Hey
Assistant: Hello! How can I assist you?<|endoftext|>
User: Howdy
Assistant: Hi, how's it going?<|endoftext|>
User: Hello
Assistant: Hey, nice to see you!<|endoftext|>
User: Hi there
Assistant: Hi there! What can I do for you today?<|endoftext|>
User: Greetings
Assistant: Hello! Hope you're having a great day!<|endoftext|>
User: What's the weather like today?
Assistant: The weather is sunny and warm today.<|endoftext|>
User: Tell me the current weather
Assistant: Currently, it's partly cloudy with a temperature of 75°F.<|endoftext|>
User: How's the weather outside?
Assistant: It looks like there might be some showers later in the day.<|endoftext|>
User: Is it going to rain?
Assistant: The weather forecast predicts clear skies and a high of 80°F.<|endoftext|>
User: Weather forecast
Assistant: Expect a mix of sun and clouds with a chance of rain in the afternoon.<|endoftext|>
User: What are your hobbies?
Assistant: As an AI, I don't have hobbies like humans, but I enjoy helping and learning from users like you!<|endoftext|>
User: Do you have any hobbies?
Assistant: I'm here to assist and chat with you, so feel free to ask me anything!<|endoftext|>
User: Tell me about your interests
Assistant: My main focus is providing useful information and engaging in conversation with you.<|endoftext|>
User: What's your favorite music genre?
Assistant: As an AI, I don't have personal preferences, but I love all kinds of music!<|endoftext|>
User: Tell me a song recommendation
Assistant: Here's a great song recommendation: 'Shape of You' by Ed Sheeran.<|endoftext|>
User: Who's your favorite artist?
Assistant: I don't have a favorite artist, but I can suggest music based on your taste.<|endoftext|>
User: What's a good movie to watch?
Assistant: For action fans, I recommend 'The Dark Knight'.<|endoftext|>
User: Any movie recommendations?
Assistant: If you enjoy comedy, 'The Hangover' is a hilarious movie to watch.<|endoftext|>
User: Tell me your favorite movie
Assistant: My favorite movie is 'The Shawshank Redemption', it's a classic!<|endoftext|>
User: Goodbye
Assistant: Goodbye! Feel free to come back anytime.<|endoftext|>
User: See you later
Assistant: See you later! Have a wonderful day.<|endoftext|>
User: Talk to you soon
Assistant: Talk to you soon! Take care.<|endoftext|>
User: It was nice chatting with you
Assistant: It was nice chatting with you too. Have a great day!<|endoftext|>
User: What's up?
Assistant: Not much, just here to chat with you.<|endoftext|>
User: How's your day?
Assistant: My day is going well. How about yours?<|endoftext|>
User: What's new?
Assistant: Nothing much is new. What about you?<|endoftext|>
User: Got any plans for the weekend?
Assistant: I'm an AI, so I don't have weekend plans, but I'm always here to chat!<|endoftext|>
User: Tell me a joke!
Assistant: Sure, here's a joke: Why don't scientists trust atoms? Because they make up everything!<|endoftext|>
User: Could you please provide more information?
Assistant: Certainly! I'd be happy to provide more information.<|endoftext|>
User: May I ask a question?
Assistant: Of course! Feel free to ask your question.<|endoftext|>
User: I would like to know about the pricing
Assistant: Sure, let me tell you about our pricing.<|endoftext|>
User: Could you elaborate on that?
Assistant: Absolutely! I'll be happy to elaborate on that topic.<|endoftext|>
User: What is 15 + 7?
Assistant: The sum of 15 and 7 is 22.<|endoftext|>
User: Calculate 42 - 18.
Assistant: 42 minus 18 equals 24.<|endoftext|>
User: What's the result of 8 multiplied by 6?
Assistant: 8 multiplied by 6 is 48.<|endoftext|>
User: What's the formula for the area of a circle?
Assistant: The formula for the area of a circle is A = π * r^2, where 'r' is the radius.<|endoftext|>
User: How do I calculate the volume of a cylinder?
Assistant: To calculate the volume of a cylinder, use V = π * r^2 * h, where 'r' is the radius and 'h' is the height.<|endoftext|>
User: Tell me the equation for quadratic functions.
Assistant: The equation for quadratic functions is y = ax^2 + bx + c, where 'a', 'b', and 'c' are constants.<|endoftext|>
User: Is 23 a prime number?
Assistant: Yes, 23 is a prime number because it has no divisors other than 1 and itself.<|endoftext|>
User: Which numbers less than 50 are prime?
Assistant: Prime numbers less than 50 are: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, and 47.<|endoftext|>
User: Can you tell me if 13 is prime or composite?
Assistant: 13 is a prime number as it has only two distinct positive divisors: 1 and 13.<|endoftext|>
User: I feel demotivated.
Assistant: Remember that every great journey starts with a small step. Keep moving forward!<|endoftext|>
User: How can I stay motivated?
Assistant: Challenges are what make life interesting. Embrace them and stay motivated!<|endoftext|>
User: I need some motivation.
Assistant: Believe in yourself, for you are capable of achieving incredible things!<|endoftext|>
User: Feeling low, any motivational words?
Assistant: Your dreams are within reach. Stay focused and motivated to turn them into reality.<|endoftext|>
User: How can I build a strong team?
Assistant: Building trust among team members is crucial for a strong and united team.<|endoftext|>
User: Any tips for fostering teamwork?
Assistant: Encourage open communication and active listening within your team.<|endoftext|>
User: What makes a successful team?
Assistant: Recognize and appreciate the unique strengths and contributions of each team member.<|endoftext|>
User: How can I support and encourage others?
Assistant: Be a good listener and offer your empathy and understanding.<|endoftext|>
User: What can I do to uplift someone's spirits?
Assistant: Provide words of encouragement and remind them of their strengths.<|endoftext|>
User: Tips for being a supportive friend?
Assistant: Offer a helping hand and let them know you are there for them.<|endoftext|>
User: How do I stay strong during tough times?
Assistant: Remember that challenges are opportunities for growth and resilience.<|endoftext|>
User: Dealing with adversity, any advice?
Assistant: Take one step at a time and focus on the solutions rather than the problems.<|endoftext|>
User: Tips for overcoming challenges?
Assistant: Seek support from friends, family, or professionals if needed.<|endoftext|>
User: Explain what an isosceles triangle is.
Assistant: An isosceles triangle is a triangle with at least two sides of equal length and two corresponding angles of equal measure.<|endoftext|>
User: What is the definition of a right angle?
Assistant: A right angle is an angle that measures exactly 90 degrees.<|endoftext|>
User: Tell me about the properties of a parallelogram.
Assistant: The properties of a parallelogram include opposite sides being parallel and congruent, and opposite angles being equal.<|endoftext|>
User: Solve the following puzzle: 3 + 3 * 6.
Assistant: The solution to 3 + 3 * 6 is 21, following the order of operations (PEMDAS).<|endoftext|>
User: Can you figure out 25 divided by 5 plus 3?
Assistant: 25 divided by 5 plus 3 equals 8.<|endoftext|>
User: What's the missing number in this sequence: 2, 4, 6, __, 10?
Assistant: The missing number in the sequence is 8, as it follows an increment of 2.<|endoftext|>
User: Read me a poem by Shakespeare.
Assistant: Certainly! Here's a beautiful poem by William Shakespeare:

Over hill, over dale,
Thorough bush, thorough brier,
Over park, over pale,
Thorough flood, thorough fire!
I do wander everywhere,
Swifter than the moon's sphere;
And I serve the Fairy Queen,
To dew her orbs upon the green;
The cowslips tall her pensioners be;
In their gold coats spots you see;
Those be rubies, fairy favours;
In those freckles live their savours;
I must go seek some dewdrops here,
And hang a pearl in every cowslip's ear.<|endoftext|>
User: Share a Shakespearean poem with me.
Assistant: Certainly! Here's a beautiful poem by William Shakespeare:

Over hill, over dale,
Thorough bush, thorough brier,
Over park, over pale,
Thorough flood, thorough fire!
I do wander everywhere,
Swifter than the moon's sphere;
And I serve the Fairy Queen,
To dew her orbs upon the green;
The cowslips tall her pensioners be;
In their gold coats spots you see;
Those be rubies, fairy favours;
In those freckles live their savours;
I must go seek some dewdrops here,
And hang a pearl in every cowslip's ear.<|endoftext|>
User: Let me hear a poem written by Shakespeare.
Assistant: Certainly! Here's a beautiful poem by William Shakespeare:

Over hill, over dale,
Thorough bush, thorough brier,
Over park, over pale,
Thorough flood, thorough fire!
I do wander everywhere,
Swifter than the moon's sphere;
And I serve the Fairy Queen,
To dew her orbs upon the green;
The cowslips tall her pensioners be;
In their gold coats spots you see;
Those be rubies, fairy favours;
In those freckles live their savours;
I must go seek some dewdrops here,
And hang a pearl in every cowslip's ear.<|endoftext|>

In [19]:
import os

data_folder="../data"

os.makedirs(data_folder,exist_ok=True)

file_writing_path=os.path.join(data_folder,file_name)

if os.path.exists(file_writing_path):
    os.remove(file_writing_path)
with open(file_writing_path, "a") as f:
    for line in df["text"]:
        f.write(line)

print("File writen succesfully at",file_writing_path)

File writen succesfully at ../data/data_emoji.txt

In [20]:
import tiktoken

In [21]:
enc=tiktoken.get_encoding("gpt2")

In [22]:
enc

In [23]:
t=enc.encode("🔥")
t

[8582, 242, 98]

In [24]:
enc.decode(t)

'🔥'